FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    mlflow==2.16.2 \
    boto3 \
    gunicorn

RUN mkdir -p /mlflow

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "--workers", "4", "mlflow.server:app"]